### ISSUE TITLE
Credit Card payment method not working

### ISSUE THREAD

**Issue by joachimVT** [mollie/magento2-hyva-react-checkout#3]
Hi

We integrated the Hyva react checkout with magento2-hyva-react-checkout package included. 
Everything works as expected except for the Credit card payment method. When we place an order with this method it just redirects automatically to the success page without entering mollie payment page. All other methods (Bancontact , Ideal) work as expected.  

Mollie version: mollie/magento2
Magento version: 2.3.7-p4
Luma theme based. 

Any ideas what's causing this issue? 

**Update**
When i enable the Mollie components, the Credit Card payment works as expected. So there's only an issue when the components are disabled. This error message appears:
_Not all required components are mounted yet. Card holder, card number, expiry date, and verification code are required._

I Tried to debug but couldn't really find anything.

**Comment by Frank-Magmodules** [comment]
Hello, @joachimVT! Apologies for not getting in touch sooner regarding this matter; it appears I overlooked it. Is the issue still pertinent, and do you require assistance with it? Just let me know!

**Comment by Frank-Magmodules** [comment]
Due to inactivity, I am closing this issue for now. 
Please feel free to reopen the matter once you have additional information and/or still require assistance.
