### ISSUE TITLE
Surcharge is not visible in the react checkout totals and the total is not updated after choosing for example PayPal

### ISSUE THREAD

**Issue by erwinschaap** [mollie/magento2-hyva-react-checkout#5]
When I have a surcharge of 3% in the backoffice for paypal and I choose paypal as payment method, the totals are not updated and there is no information about the surcharge costs for the customer

PS. if I change the payment method to another payment method, there is not always a new graphql request triggered. Is that correct behaviour?

**Comment by erwinschaap** [comment]
@Frank-Magmodules could you please help us out with this?

**Comment by Frank-Magmodules** [comment]
Hello @erwinschaap, thanks for reaching out! I'll get back to you shortly with a comprehensive response.

**Comment by erwinschaap** [comment]
@Frank-Magmodules Do you have news about this ticket?

**Comment by Frank-Magmodules** [comment]
HI @erwinschaap ,

Thank you for opening this issue and your patience here. 
We have investigated this issue, and to add another row to the totals we should override this template file:
https://github.com/hyva-themes/magento2-react-checkout/blob/main/src/reactapp/src/components/totals/Totals.jsx

As far as we know, this is not possible. At least, not from an extension point of view. 
So, unfortunately, we can’t fix this issue for you, therefore, we will close this issue.
