### ISSUE TITLE
Payment method Creditcards requires MollieComponent to be set to true in the react checkout but returns errors when it is false

### ISSUE THREAD

**Issue by erwinschaap** [mollie/magento2-hyva-react-checkout#6]
Our situation:
Creditcards enabled
Mollie components for creditcards false

We dont want to use Mollie Components and the customer should only fill in creditcard details into Mollie

In our situation the following error has been fired:
Not all required components are mounted yet. Card holder, card number, expiry date, and verification code are required.

Please fix this, because this setup was working in the normal Luma checkout.

**Comment by erwinschaap** [comment]
@Frank-Magmodules This issue is maybe quite important

**Comment by Frank-Magmodules** [comment]
Hi @erwinschaap , sure, will investigate this and get back to you.

**Comment by Frank-Magmodules** [comment]
Hi there, @erwinschaap! Thanks a lot for your patience regarding this issue. 

I'm happy to inform you that we have successfully reproduced and fixed your issue within the [latest release](https://github.com/mollie/magento2-hyva-react-checkout/releases/tag/1.2.0) of the plugin. In addition to resolving the Credit Card component issue, we've also added support for some new payment methods. 

I'm closing this issue for now, but please feel free to reopen it if necessary. 
Thanks again for your patience!

**Comment by erwinschaap** [comment]
I think there is something wrong with the code in the release (you can view the renderers.js in de main branch and the creditcardRenderer is not being used
